import type { FoodItemType } from "./food-item.contract";

// Example food definitions showing the food-unit hierarchy approach
export const exampleFoodItems: FoodItemType[] = [
    {
        foodId: "apple-001",
        userId: "user-123",
        name: "Apple",
        category: "fruits",
        description: "Fresh red or green apples",
        units: [
            {
                unitId: "apple-medium",
                unitName: "medium",
                unitDescription: "1 medium apple (about 180g)",
                nutritionPerUnit: {
                    calories: 95,
                    protein: 0.5,
                    carbohydrates: 25,
                    fat: 0.3,
                    fiber: 4,
                    sugar: 19,
                },
                isDefault: true,
                estimatedWeight: 180,
                source: "database",
            },
            {
                unitId: "apple-slice",
                unitName: "slice",
                unitDescription: "1 thin slice",
                nutritionPerUnit: {
                    calories: 8,
                    protein: 0.04,
                    carbohydrates: 2,
                    fat: 0.02,
                    fiber: 0.3,
                    sugar: 1.5,
                },
                isDefault: false,
                estimatedWeight: 15,
                source: "database",
            },
            {
                unitId: "apple-large",
                unitName: "large",
                unitDescription: "1 large apple (about 240g)",
                nutritionPerUnit: {
                    calories: 125,
                    protein: 0.7,
                    carbohydrates: 33,
                    fat: 0.4,
                    fiber: 5,
                    sugar: 25,
                },
                isDefault: false,
                estimatedWeight: 240,
                source: "database",
            },
        ],
        isPublic: true,
    },
    {
        foodId: "bread-001",
        userId: "user-123",
        name: "Whole Wheat Bread",
        category: "grains",
        description: "Standard whole wheat sandwich bread",
        units: [
            {
                unitId: "bread-slice",
                unitName: "slice",
                unitDescription: "1 slice (about 28g)",
                nutritionPerUnit: {
                    calories: 80,
                    protein: 4,
                    carbohydrates: 14,
                    fat: 1.5,
                    fiber: 3,
                    sugar: 2,
                    sodium: 160,
                },
                isDefault: true,
                estimatedWeight: 28,
                source: "package_label",
            },
            {
                unitId: "bread-loaf",
                unitName: "loaf",
                unitDescription: "1 whole loaf (about 680g)",
                nutritionPerUnit: {
                    calories: 1940,
                    protein: 97,
                    carbohydrates: 340,
                    fat: 36,
                    fiber: 73,
                    sugar: 49,
                    sodium: 3880,
                },
                isDefault: false,
                estimatedWeight: 680,
                source: "package_label",
                notes: "Calculated from 24 slices per loaf",
            },
        ],
        isPublic: true,
    },
    {
        foodId: "flour-001",
        userId: "user-123",
        name: "All-Purpose Flour",
        category: "grains",
        description: "Standard all-purpose white flour",
        units: [
            {
                unitId: "flour-cup",
                unitName: "cup",
                unitDescription: "1 cup (about 120g)",
                nutritionPerUnit: {
                    calories: 455,
                    protein: 13,
                    carbohydrates: 95,
                    fat: 1.2,
                    fiber: 3.4,
                    sugar: 0.3,
                    sodium: 3,
                },
                isDefault: true,
                estimatedWeight: 120,
                source: "user_measured",
                notes: "Measured with my kitchen scale",
            },
            {
                unitId: "flour-tablespoon",
                unitName: "tablespoon",
                unitDescription: "1 tablespoon (about 8g)",
                nutritionPerUnit: {
                    calories: 30,
                    protein: 0.9,
                    carbohydrates: 6.3,
                    fat: 0.08,
                    fiber: 0.2,
                    sugar: 0.02,
                    sodium: 0.2,
                },
                isDefault: false,
                estimatedWeight: 8,
                source: "user_measured",
            },
            {
                unitId: "flour-100g",
                unitName: "100g",
                unitDescription: "100 grams",
                nutritionPerUnit: {
                    calories: 364,
                    protein: 10,
                    carbohydrates: 76,
                    fat: 1,
                    fiber: 2.7,
                    sugar: 0.3,
                    sodium: 2,
                },
                isDefault: false,
                estimatedWeight: 100,
                source: "package_label",
            },
        ],
        isPublic: true,
    },
    {
        foodId: "chicken-001",
        userId: "user-123",
        name: "Chicken Breast",
        category: "proteins",
        description: "Boneless, skinless chicken breast",
        units: [
            {
                unitId: "chicken-breast",
                unitName: "breast",
                unitDescription: "1 medium breast (about 150g)",
                nutritionPerUnit: {
                    calories: 248,
                    protein: 46,
                    carbohydrates: 0,
                    fat: 5.4,
                    fiber: 0,
                    sugar: 0,
                    sodium: 104,
                },
                isDefault: true,
                estimatedWeight: 150,
                source: "database",
            },
            {
                unitId: "chicken-100g",
                unitName: "100g",
                unitDescription: "100 grams",
                nutritionPerUnit: {
                    calories: 165,
                    protein: 31,
                    carbohydrates: 0,
                    fat: 3.6,
                    fiber: 0,
                    sugar: 0,
                    sodium: 74,
                },
                isDefault: false,
                estimatedWeight: 100,
                source: "database",
            },
        ],
        isPublic: true,
    },
];

// Example usage scenarios
export const exampleUsages = [
    {
        description: "Adding 2 medium apples to a recipe",
        foodId: "apple-001",
        unitId: "apple-medium",
        quantity: 2,
        expectedCalories: 190, // 2 × 95
        displayText: "2 medium apples",
    },
    {
        description: "Adding 1 cup of flour to a recipe",
        foodId: "flour-001",
        unitId: "flour-cup",
        quantity: 1,
        expectedCalories: 455,
        displayText: "1 cup all-purpose flour",
    },
    {
        description: "Adding 6 slices of apple to a salad",
        foodId: "apple-001",
        unitId: "apple-slice",
        quantity: 6,
        expectedCalories: 48, // 6 × 8
        displayText: "6 apple slices",
    },
];
