version: "3.8"

services:
    postgres:
        image: postgres:15-alpine
        container_name: daily-schedule-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: daily-schedule-db
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init-db:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d daily-schedule-db"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    postgres_data:
        driver: local
